# Docker Compose override for build-time migrations
# Usage: docker-compose -f docker-compose.yml -f docker-compose.build-migrations.yml up --build

version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.build-migrations
      args:
        - POSTGRES_SERVER=db
        - POSTGRES_USER=recaller
        - POSTGRES_PASSWORD=recaller
        - POSTGRES_DB=recaller
        - POSTGRES_PORT=5432
    # Override to remove the entrypoint-based migration since it's done at build time
    entrypoint: []
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
