---
# Production Environment Configuration
version: "1.0.0"
category: "environment"
type: "production"
name: "Production Environment Settings"
description: "Production-specific configuration settings"
author: "Recaller Team"
last_updated: "2025-08-15"
deprecated: false

# Database Configuration (Production overrides)
database:
  host: "${POSTGRES_SERVER}"
  port: "${POSTGRES_PORT:5432}"
  user: "${POSTGRES_USER}"
  password: "${POSTGRES_PASSWORD}"
  name: "${POSTGRES_DB}"
  pool_size: "${DB_POOL_SIZE:20}"
  max_overflow: "${DB_MAX_OVERFLOW:30}"
  pool_timeout: "${DB_POOL_TIMEOUT:60}"
  ssl_mode: "${DB_SSL_MODE:require}"

# Security Configuration (Production)
security:
  secret_key: "${SECRET_KEY}"  # Required in production
  access_token_expire_minutes: "${ACCESS_TOKEN_EXPIRE_MINUTES:60}"
  jwt_algorithm: "${JWT_ALGORITHM:HS256}"
  require_https: "${REQUIRE_HTTPS:true}"

# Redis Configuration (Production)
redis:
  url: "${REDIS_URL}"
  cache_ttl: "${REDIS_CACHE_TTL:7200}"
  max_connections: "${REDIS_MAX_CONNECTIONS:50}"

# CORS Configuration (Restricted)
cors:
  allowed_origins: "${CORS_ALLOWED_ORIGINS}"  # Must be explicitly set
  allowed_methods: "${CORS_ALLOWED_METHODS:GET,POST,PUT,DELETE}"
  allowed_headers: "${CORS_ALLOWED_HEADERS:Content-Type,Authorization,X-Tenant-ID}"
  allow_credentials: "${CORS_ALLOW_CREDENTIALS:true}"

# Application Configuration
application:
  project_name: "${PROJECT_NAME:Recaller}"
  version: "${VERSION:1.0.0}"
  api_v1_str: "${API_V1_STR:/api/v1}"
  debug_mode: "${DEBUG:false}"
  log_level: "${LOG_LEVEL:WARNING}"

# Feature Flags (Production)
features:
  hot_reload: "${ENABLE_HOT_RELOAD:false}"
  debug_toolbar: "${DEBUG_TOOLBAR:false}"
  metrics_enabled: "${METRICS_ENABLED:true}"
  rate_limiting: "${RATE_LIMITING:true}"

# Performance Configuration
performance:
  cache_ttl: "${CACHE_TTL:3600}"
  session_timeout: "${SESSION_TIMEOUT:1800}"
  request_timeout: "${REQUEST_TIMEOUT:30}"